<?php

/*
|--------------------------------------------------------------------------
| Version and build information
|
| Generated by scripts/build_info.bash into a gitignored .build_info.json, so that
| releasing never touches a tracked file. When that file is absent - a plain working
| copy, or a checkout with no build step - fall back to .version with a ".dev" label.
|
| .version holds major.minor and is the only part a human edits. The patch number is
| the commit count, and the hash and date describe the build.
|--------------------------------------------------------------------------
*/

$buildInfoFile = __DIR__ . '/../../../.build_info.json';
$buildInfo = [];
if (is_file($buildInfoFile)) {
    $decodedBuildInfo = json_decode((string) file_get_contents($buildInfoFile), true);
    $buildInfo = (is_array($decodedBuildInfo) ? $decodedBuildInfo : []);
}

if (!empty($buildInfo)) {
    $config['version'] = $buildInfo['version'] ?? '';
    $config['git_commit_hash'] = $buildInfo['git_commit_hash'] ?? '';
    $config['git_commit_date'] = $buildInfo['git_commit_date'] ?? '';
    $config['asset_version'] = (
        $buildInfo['asset_version']
        ?? substr((string) $config['git_commit_hash'], 0, 7)
    );
} else {
    $versionFile = __DIR__ . '/../../../.version';
    $majorMinor = (
        is_file($versionFile)
        ? trim((string) file_get_contents($versionFile))
        : '0.0'
    );

    $config['version'] = "v{$majorMinor}.dev";
    $config['git_commit_hash'] = '';
    $config['git_commit_date'] = '';

    // No build to pin assets to, so bust the cache on every request
    $config['asset_version'] = time();
}

// An explicit dev environment always busts asset caches, build info or not
if (($config['environment'] ?? '') === 'dev') {
    $config['asset_version'] = time();
}
