const path = require('path');
const fs = require('fs');
const rspack = require('@rspack/core');

const ROOT = __dirname;
const APPS_ROOT = path.resolve(ROOT, 'src');

/**
 * Build metadata, generated by scripts/build_info.bash into a gitignored file.
 *
 * Absent in a plain working copy, so fall back to .version with a ".dev" label - the same
 * rule src/<App>/Config/App.php applies, so php and js always agree.
 */
function buildInfo() {
    const buildInfoFile = path.resolve(ROOT, '.build_info.json');
    if (fs.existsSync(buildInfoFile)) {
        try {
            return JSON.parse(fs.readFileSync(buildInfoFile, 'utf8'));
        } catch {
            // Fall through to the .dev label rather than failing the build
        }
    }

    const versionFile = path.resolve(ROOT, '.version');
    const majorMinor = fs.existsSync(versionFile)
        ? fs.readFileSync(versionFile, 'utf8').trim()
        : '0.0';

    return {
        version: `v${majorMinor}.dev`,
        git_commit_hash: '',
        git_commit_date: '',
    };
}

/**
 * Every src/<App>/Public/assets/src is one application's front end.
 *
 * Entry points are the files sitting directly in that directory - everything shared lives
 * in a subdirectory (base/, react/, ...) and is imported rather than built on its own. So
 * assets/src/defaults.ts becomes dist/js/defaults.min.js, which is the name a view passes
 * as js_include.
 */
function discoverApps() {
    if (fs.existsSync(APPS_ROOT) === false) {
        return [];
    }

    return fs
        .readdirSync(APPS_ROOT, { withFileTypes: true })
        .filter((item) => item.isDirectory())
        .map((item) => {
            const name = item.name;
            const srcDir = path.join(APPS_ROOT, name, 'Public/assets/src');
            if (fs.existsSync(srcDir) === false) {
                return null;
            }

            const entry = {};
            for (const file of fs.readdirSync(srcDir, { withFileTypes: true })) {
                if (file.isFile() === false) {
                    continue;
                }
                if (/\.(tsx?|jsx?)$/.test(file.name) === false || file.name.endsWith('.d.ts')) {
                    continue;
                }

                entry[file.name.replace(/\.(tsx?|jsx?)$/, '')] = './assets/src/' + file.name;
            }

            return (Object.keys(entry).length === 0 ? null : { name, srcDir, entry });
        })
        .filter(Boolean);
}

/**
 * One compiler per application.
 *
 * Kept as separate configurations rather than one with a shared output directory, so that
 * each application gets its own vendors chunk and its own `clean` - a single compiler
 * writing into src/ would have to be trusted not to clean the source tree.
 */
function configForApp(app, mode, info) {
    const isProd = mode === 'production';
    const appPublic = path.resolve(APPS_ROOT, app.name, 'Public');

    return {
        name: app.name,
        target: 'browserslist',
        mode,
        bail: isProd,
        context: appPublic,
        entry: app.entry,
        output: {
            clean: true,
            devtoolModuleFilenameTemplate: '[resource-path]?[loaders]',
            filename: isProd ? '[name].min.js' : '[name].bundle.js',
            path: path.join(appPublic, 'assets/dist/js'),
            library: {
                type: 'var',
                name: '[name]Module',
            },
        },
        resolve: {
            extensions: ['.ts', '.tsx', '.js', '.jsx'],
            alias: {
                base: path.join(app.srcDir, 'base/ts'),
            },
        },
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    exclude: /node_modules/,
                    loader: 'builtin:swc-loader',
                    options: {
                        jsc: {
                            parser: { syntax: 'typescript', tsx: true },
                            // Automatic runtime, so a .tsx file needs no `import React`
                            transform: { react: { runtime: 'automatic' } },
                            target: 'es2022',
                        },
                    },
                },
                {
                    test: /\.jsx?$/,
                    exclude: /node_modules/,
                    loader: 'builtin:swc-loader',
                    options: {
                        jsc: {
                            parser: { syntax: 'ecmascript', jsx: true },
                            transform: { react: { runtime: 'automatic' } },
                            target: 'es2022',
                        },
                    },
                },
            ],
        },
        optimization: {
            splitChunks: {
                cacheGroups: {
                    vendors: {
                        test: /[\\/]node_modules[\\/]/,
                        name: 'vendors',
                        chunks: 'all',
                        priority: 10,
                    },
                    commons: {
                        test: /[\\/]assets[\\/]src[\\/]base[\\/]ts[\\/]/,
                        name: 'commons',
                        chunks: 'all',
                        minChunks: 2,
                        priority: 5,
                        reuseExistingChunk: true,
                    },
                },
            },
            usedExports: true,
            sideEffects: true,
            // swc does the minifying; no separate terser plugin
            minimize: isProd,
        },
        plugins: [
            new rspack.DefinePlugin({
                APP_ENV: JSON.stringify(mode),
                APP_NAME: JSON.stringify(app.name),
                APP_VERSION: JSON.stringify(info.version || ''),
                APP_GIT_COMMIT_HASH: JSON.stringify(info.git_commit_hash || ''),
                APP_GIT_COMMIT_DATE: JSON.stringify(info.git_commit_date || ''),
            }),
        ],
        stats: { colors: true, preset: 'errors-warnings' },
        performance: { hints: false },
        devtool: 'source-map',
        watchOptions: {
            ignored: /node_modules/,
        },
    };
}

/**
 * Built fresh per invocation. The webpack config this replaced mutated a module-level
 * object inside its export, so state leaked between builds in watch mode.
 */
module.exports = (env, argv) => {
    const mode = argv.mode === 'production' ? 'production' : 'development';
    const info = buildInfo();

    // --app Shop, or APP=Shop, builds one application instead of all of them
    const only = argv.app || process.env.APP || '';
    const apps = discoverApps().filter((app) => only === '' || app.name === only);

    if (apps.length === 0) {
        throw new Error(
            only === ''
                ? 'No applications found under src/*/Public/assets/src'
                : `No application named "${only}" under src/`
        );
    }

    // An array is a multi-compiler build: rspack runs them in one invocation, and each
    // application keeps its own output directory, vendors chunk and clean
    return apps.map((app) => configForApp(app, mode, info));
};
