const path = require('path');
const fs = require('fs');
const rspack = require('@rspack/core');

const ROOT = __dirname;
const SRC = path.resolve(ROOT, 'src/Application/Public/assets/src');

/**
 * Build metadata, generated by scripts/build_info.bash into a gitignored file.
 *
 * Absent in a plain working copy, so fall back to .version with a ".dev" label - the same
 * rule src/Application/Config/App.php applies, so php and js always agree.
 */
function buildInfo() {
    const buildInfoFile = path.resolve(ROOT, '.build_info.json');
    if (fs.existsSync(buildInfoFile)) {
        try {
            return JSON.parse(fs.readFileSync(buildInfoFile, 'utf8'));
        } catch {
            // Fall through to the .dev label rather than failing the build
        }
    }

    const versionFile = path.resolve(ROOT, '.version');
    const majorMinor = fs.existsSync(versionFile)
        ? fs.readFileSync(versionFile, 'utf8').trim()
        : '0.0';

    return {
        version: `v${majorMinor}.dev`,
        git_commit_hash: '',
        git_commit_date: '',
    };
}

/**
 * Built fresh per invocation. The webpack config this replaced mutated a module-level
 * object inside its export, so state leaked between builds in watch mode.
 */
module.exports = (env, argv) => {
    const mode = argv.mode === 'production' ? 'production' : 'development';
    const isProd = mode === 'production';
    const info = buildInfo();

    return {
        target: 'browserslist',
        mode,
        bail: isProd,
        context: path.resolve(ROOT, 'src/Application/Public'),
        entry: {
            defaults: './assets/src/index.ts',
        },
        output: {
            clean: true,
            devtoolModuleFilenameTemplate: '[resource-path]?[loaders]',
            filename: isProd ? '[name].min.js' : '[name].bundle.js',
            path: path.resolve(ROOT, 'src/Application/Public/assets/dist/js/'),
            library: {
                type: 'var',
                name: '[name]Module',
            },
        },
        resolve: {
            extensions: ['.ts', '.tsx', '.js', '.jsx'],
            alias: {
                base: path.resolve(SRC, 'base/ts'),
            },
        },
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    exclude: /node_modules/,
                    loader: 'builtin:swc-loader',
                    options: {
                        jsc: {
                            parser: { syntax: 'typescript', tsx: true },
                            target: 'es2022',
                        },
                    },
                },
                {
                    test: /\.jsx?$/,
                    exclude: /node_modules/,
                    loader: 'builtin:swc-loader',
                    options: {
                        jsc: {
                            parser: { syntax: 'ecmascript', jsx: true },
                            target: 'es2022',
                        },
                    },
                },
            ],
        },
        optimization: {
            splitChunks: {
                cacheGroups: {
                    // The webpack version tested against assets/base/js, a path that does
                    // not exist - the real one is assets/src/base/ts - so only the
                    // node_modules alternative ever matched.
                    vendors: {
                        test: /[\\/]node_modules[\\/]/,
                        name: 'vendors',
                        chunks: 'all',
                        priority: 10,
                    },
                    commons: {
                        test: /[\\/]assets[\\/]src[\\/]base[\\/]ts[\\/]/,
                        name: 'commons',
                        chunks: 'all',
                        minChunks: 2,
                        priority: 5,
                        reuseExistingChunk: true,
                    },
                },
            },
            usedExports: true,
            sideEffects: true,
            // swc does the minifying; no separate terser plugin
            minimize: isProd,
        },
        plugins: [
            new rspack.DefinePlugin({
                APP_ENV: JSON.stringify(mode),
                APP_VERSION: JSON.stringify(info.version || ''),
                APP_GIT_COMMIT_HASH: JSON.stringify(info.git_commit_hash || ''),
                APP_GIT_COMMIT_DATE: JSON.stringify(info.git_commit_date || ''),
            }),
        ],
        stats: { colors: true },
        performance: { hints: false },
        devtool: 'source-map',
        watchOptions: {
            ignored: /node_modules/,
        },
    };
};
