/**
 * Compile-time constants injected by the bundler's DefinePlugin.
 *
 * APP_ENV comes from the environment; the rest come from .build_info.json, generated by
 * scripts/build_info.bash. All of them are replaced with string literals at build time,
 * so nothing reads a file at runtime.
 */

declare const APP_ENV: string;
declare const APP_VERSION: string;
declare const APP_GIT_COMMIT_HASH: string;
declare const APP_GIT_COMMIT_DATE: string;
